title: Groxie
author: Heidi
email: heidi@groxie.com
description: > # this means to ignore newlines until "baseurl:"
  building community and reducing health disparities by making transit easier to use

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-midnight
